#!/bin/bash

WALLDIR=/usr/share/backgrounds/
WALL=$(ls $WALLDIR | fzf -e)
XDG_CONFIG_HOME="$HOME/.config"
SWAYCONF="$XDG_CONFIG_HOME/sway/config"

if [ ! -z "$WALL" ]; then
    WALLSTRING="$WALLDIR$WALL"
    # set wall to lockscreen
    sed -i "/^set \$LOCKBG.*/c set \$LOCKBG $WALLSTRING" "$SWAYCONF"
    # send bg to swaybg
    swaymsg "output * bg $WALLSTRING fill"
    # set bg to persist
    sed -i "/^output \* bg/c output * bg $WALLSTRING fill" $SWAYCONF
fi
