#!/bin/bash

echo " • Symbolic linking..."
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd

echo " • Downloading submodules..."
git submodule update --init --recursive

# echo " • Initializing conda..."
# conda init "$(basename "${SHELL}")"

echo "  Installation complete."
