#!/bin/bash

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="home,linux"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

echo " • Is this a fresh installation? (Y/n) •"
read -r res
if [[ $res == "Y" || $res == "y" ]]; then
    STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install_new
else
    STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
    
    echo ""
    if [[ "$XDG_CURRENT_DESKTOP" == "i3"* ]]; then
        echo "• Installing Touchpad Gestures..."
        sudo tee /usr/share/X11/xorg.conf.d/90-touchpad.conf <<-EOF >/dev/null 2>&1
            Section "InputClass"
                Identifier "touchpad"
                MatchIsTouchpad "on"
                Driver "libinput"
                Option "Tapping" "on"
                Option "NaturalScrolling" "true"
                Option "TappingButtonMap" "lrm" # 1/2/3 finger, for 3-finger middle lrm
            EndSection
		EOF

        echo ""
        echo "• Disabling Mouse Acceleration..."
        sudo tee /usr/share/X11/xorg.conf.d/50-mouse-disable-accel.conf <<-EOF >/dev/null 2>&1
            Section "InputClass"
                Identifier "mouse-disable-accel"
                Driver "libinput"
                MatchIsPointer "yes"
                Option "AccelProfile" "flat"
            EndSection
		EOF
    fi
    echo ""
fi
