#!/usr/bin/env zsh

if [[ "$OSTYPE" == "darwin"* ]]; then
    alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
    alias up="omz update && brew upgrade && brew upgrade --cask --greedy && mas upgrade"
    alias brew-clean='sudo rm -r /Users/y/Library/Caches/Homebrew/downloads/*'
    alias roque-conn="$HOME/.config/script/roque"
    alias tango-start="$HOME/.config/script/tango-start"
    alias tango-stop="$HOME/.config/script/tango-stop"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    alias myip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
    alias up="sudo apt update && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo snap refresh && omz update -y && armv"
    alias ins="sudo apt install -y"
    alias purge="sudo apt purge -y"
    alias als="sudo apt list --installed | rg"
    alias armv="sudo apt autoremove -y"
    alias gedit='gnome-text-editor'
else
    echo " ERROR: Unsupported operating system!"
    echo " OS: $OSTYPE"
fi

alias la='ls -AF'
alias l='ls -AlF'
alias ta='tmux attach'
alias zr='source $HOME/.zshrc'
alias py='python'
alias d="cd $HOME/Developer"
alias gs='git status'
alias gp='git push'
alias gpl='git pull --rebase'
alias gr='git restore'
alias gc='git commit -m'
alias ga='git add'
alias gd='git diff'
alias gl='git log'
alias gck="git_checkout"
alias top='htop'
alias lr='l | rg'
alias tango='ssh -p 41061 -X root@localhost'
alias tango-fs='fs root localhost 41061'
alias lzd='lazydocker'
alias doti="$HOME/.dotfiles/install"
