#!/usr/bin/env bash

#addToPathFront /home/
addToPath $HOME/.local/scripts
addToPath $HOME/.cargo/bin

if [[ "$OSTYPE" == "darwin"* ]]; then
	addToPath /opt/homebrew
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	addToPath $HOME/.screenlayout
fi
