#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	if [[ `hostname` == "mbpro" ]]; then
	        selected=$(find ~/.screenlayout/mbpro/ -type f | fzf --height 20%)
	elif [[ `hostname` == "fatty" ]]; then
		selected=$(find ~/.screenlayout/fatty/ -type f | fzf --height 20%)
	else
        	echo "Notebook unsupported!"
	fi
fi

if [[ -z $selected ]]; then
	exit 0
else
	sh $selected
	layout=$(grep -A 0 "#" $selected | tail -n 1 | cut -c 3-)
	#echo "Applied screen layout ${layout}"
	notify-send -t 1300 "Applied screen layout ${layout}"
fi
